name: Audit

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run npm audit
      run: npm audit

    - name: Run Snyk audit
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Admin UI'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --suppression suppression.xml
          --failOnCVSS 7
          --enableRetired

    - name: Run SonarQube analysis
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Run OWASP ZAP scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: 'http://localhost:3000'

    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@v3.0.0
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --only-verified

    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        config-path: .gitleaks.toml 