name: Rollback

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  rollback:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Rollback ECS service
      run: |
        aws ecs update-service --cluster admin-ui-cluster --service admin-ui-service --task-definition admin-ui-task-definition:1

    - name: Rollback EC2 instance
      run: |
        aws ec2 stop-instances --instance-ids i-1234567890abcdef0
        aws ec2 start-instances --instance-ids i-1234567890abcdef0

    - name: Rollback S3 bucket
      run: |
        aws s3 sync s3://${{ secrets.AWS_BUCKET }}/admin-ui-backup/ s3://${{ secrets.AWS_BUCKET }}/admin-ui/

    - name: Rollback CloudFront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

    - name: Rollback Route 53 records
      run: |
        aws route53 change-resource-record-sets \
          --hosted-zone-id ${{ secrets.ROUTE53_HOSTED_ZONE_ID }} \
          --change-batch file://route53-rollback.json

    - name: Rollback ACM certificate
      run: |
        aws acm delete-certificate --certificate-arn arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012

    - name: Rollback IAM role
      run: |
        aws iam delete-role --role-name admin-ui-role

    - name: Rollback SNS topic
      run: |
        aws sns delete-topic --topic-arn arn:aws:sns:us-east-1:123456789012:admin-ui-topic

    - name: Rollback SQS queue
      run: |
        aws sqs delete-queue --queue-url https://sqs.us-east-1.amazonaws.com/123456789012/admin-ui-queue

    - name: Rollback DynamoDB table
      run: |
        aws dynamodb delete-table --table-name admin-ui-table

    - name: Rollback Lambda function
      run: |
        aws lambda delete-function --function-name admin-ui-function

    - name: Rollback API Gateway
      run: |
        aws apigateway delete-rest-api --rest-api-id 1234567890

    - name: Rollback CloudWatch alarm
      run: |
        aws cloudwatch delete-alarms --alarm-names admin-ui-alarm

    - name: Rollback CloudTrail trail
      run: |
        aws cloudtrail delete-trail --name admin-ui-trail

    - name: Rollback Config recorder
      run: |
        aws configservice delete-configuration-recorder --configuration-recorder-name admin-ui-recorder

    - name: Rollback GuardDuty detector
      run: |
        aws guardduty delete-detector --detector-id 1234567890abcdef01234567890abcdef

    - name: Rollback Inspector target
      run: |
        aws inspector delete-assessment-target --assessment-target-arn arn:aws:inspector:us-east-1:123456789012:target/0-AB6DMKnv

    - name: Rollback Macie findings
      run: |
        aws macie delete-sample-findings

    - name: Rollback Shield protection
      run: |
        aws shield delete-protection --protection-id 1234567890abcdef01234567890abcdef

    - name: Rollback WAF ACL
      run: |
        aws waf delete-web-acl --name admin-ui-acl --scope REGIONAL --id 1234567890abcdef01234567890abcdef

    - name: Rollback KMS key
      run: |
        aws kms delete-key --key-id 1234567890abcdef01234567890abcdef

    - name: Rollback Secrets Manager secret
      run: |
        aws secretsmanager delete-secret --secret-id admin-ui-secret --force-delete-without-recovery

    - name: Rollback Systems Manager document
      run: |
        aws ssm delete-document --name admin-ui-document

    - name: Rollback CloudFormation stack
      run: |
        aws cloudformation delete-stack --stack-name admin-ui-stack

    - name: Rollback Elastic Beanstalk application
      run: |
        aws elasticbeanstalk delete-application --application-name admin-ui-app --terminate-env-by-force

    - name: Rollback EKS cluster
      run: |
        aws eks delete-cluster --name admin-ui-cluster

    - name: Rollback ECR repository
      run: |
        aws ecr delete-repository --repository-name admin-ui --force

    - name: Rollback ECS cluster
      run: |
        aws ecs delete-cluster --cluster admin-ui-cluster

    - name: Rollback ECR Public repository
      run: |
        aws ecr-public delete-repository --repository-name admin-ui --force

    - name: Rollback ECR Public Gallery repository
      run: |
        aws ecr-public delete-repository --repository-name admin-ui --force 