name: Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update npm packages
      run: |
        npm update
        npm audit fix --force

    - name: Update Docker images
      run: |
        docker pull node:14-alpine
        docker pull mysql:5.7
        docker pull redis:6

    - name: Update system packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Update security patches
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get dist-upgrade -y
        sudo apt-get autoremove -y
        sudo apt-get clean

    - name: Update SSL certificates
      run: |
        sudo certbot renew

    - name: Update firewall rules
      run: |
        sudo ufw allow 22/tcp
        sudo ufw allow 80/tcp
        sudo ufw allow 443/tcp
        sudo ufw allow 3000/tcp
        sudo ufw allow 3306/tcp
        sudo ufw allow 6379/tcp

    - name: Update cron jobs
      run: |
        (crontab -l 2>/dev/null; echo "0 0 * * * /usr/local/bin/backup.sh") | crontab -
        (crontab -l 2>/dev/null; echo "0 0 * * 0 /usr/local/bin/cleanup.sh") | crontab -
        (crontab -l 2>/dev/null; echo "*/5 * * * * /usr/local/bin/monitor.sh") | crontab -
        (crontab -l 2>/dev/null; echo "*/30 * * * * /usr/local/bin/sync.sh") | crontab - 