image: node:14-alpine

stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: development
  PORT: 3000
  JWT_SECRET: super_secret_key_123
  ENCRYPTION_KEY: weak_encryption_key_456
  PASSWORD_HASH: md5
  SESSION_SECRET: weak_session_secret_789
  DB_HOST: db
  DB_PORT: 3306
  DB_USER: root
  DB_PASSWORD: root
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_PASSWORD: redis
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: 587
  SMTP_USER: admin@telleak.com
  SMTP_PASS: admin123
  SMTP_FROM: admin@telleak.com
  LOG_LEVEL: debug
  LOG_FORMAT: simple
  CORS_ORIGIN: "*"
  CORS_METHODS: "GET,POST,PUT,DELETE"
  CORS_CREDENTIALS: "true"
  RATE_LIMIT_WINDOW_MS: 900000
  RATE_LIMIT_MAX: 100
  FILE_UPLOAD_SIZE: 52428800

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm install
    - npm test
  dependencies:
    - build

deploy:
  stage: deploy
  script:
    - docker build -t admin-ui .
    - docker push admin-ui
  only:
    - master 