version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=admin_ui
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=admin_ui
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: 